source 'http://rubygems.org'

gem 'rails', '3.0.16'

gem 'sqlite3'

group :test do
  gem 'test-unit', '1.2.3' # yes, I need to support this.
end

group :test, :development do
  gem "rspec-rails", "~> 2.0"
end

